/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: R3indeer (https://sketchfab.com/R3indeer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spotlight-bf2894cc5af04be6a57cc2ff66e0bbee
Title: Spotlight
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Spotlight(props) {
  const { nodes, materials } = useGLTF("/spotlight.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 64.603, 0.148]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_MAT_SceneProps_0.geometry}
            material={materials.MAT_SceneProps}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_MAT_Lightbeam_0.geometry}
            material={materials.MAT_Lightbeam}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder000_MAT_SceneProps_0.geometry}
          material={materials.MAT_SceneProps}
          position={[0, 64.603, 0.148]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/spotlight.glb");
